// Surah information with name and number of ayahs
export const surahData = [
  { number: 1, name: "1. Al-Fatihah (The Opening)", ayahs: 7 },
  { number: 2, name: "2. Al-Baqarah (The Cow)", ayahs: 286 },
  { number: 3, name: "3. Aal-Imran (The Family of Imran)", ayahs: 200 },
  { number: 4, name: "4. An-Nisa (The Women)", ayahs: 176 },
  { number: 5, name: "5. Al-Ma'idah (The Table Spread)", ayahs: 120 },
  { number: 6, name: "6. Al-An'am (The Cattle)", ayahs: 165 },
  { number: 7, name: "7. Al-A'raf (The Heights)", ayahs: 206 },
  { number: 8, name: "8. Al-Anfal (The Spoils of War)", ayahs: 75 },
  { number: 9, name: "9. At-Tawbah (The Repentance)", ayahs: 129 },
  { number: 10, name: "10. Yunus (Jonah)", ayahs: 109 },
  { number: 11, name: "11. Hud (Hud)", ayahs: 123 },
  { number: 12, name: "12. Yusuf (Joseph)", ayahs: 111 },
  { number: 13, name: "13. Ar-Ra'd (The Thunder)", ayahs: 43 },
  { number: 14, name: "14. Ibrahim (Abraham)", ayahs: 52 },
  { number: 15, name: "15. Al-Hijr (The Rocky Tract)", ayahs: 99 },
  { number: 16, name: "16. An-Nahl (The Bee)", ayahs: 128 },
  { number: 17, name: "17. Al-Isra (The Night Journey)", ayahs: 111 },
  { number: 18, name: "18. Al-Kahf (The Cave)", ayahs: 110 },
  { number: 19, name: "19. Maryam (Mary)", ayahs: 98 },
  { number: 20, name: "20. Ta-Ha (Ta-Ha)", ayahs: 135 },
  { number: 21, name: "21. Al-Anbiya (The Prophets)", ayahs: 112 },
  { number: 22, name: "22. Al-Hajj (The Pilgrimage)", ayahs: 78 },
  { number: 23, name: "23. Al-Mu'minun (The Believers)", ayahs: 118 },
  { number: 24, name: "24. An-Nur (The Light)", ayahs: 64 },
  { number: 25, name: "25. Al-Furqan (The Criterion)", ayahs: 77 },
  { number: 26, name: "26. Ash-Shu'ara (The Poets)", ayahs: 227 },
  { number: 27, name: "27. An-Naml (The Ant)", ayahs: 93 },
  { number: 28, name: "28. Al-Qasas (The Stories)", ayahs: 88 },
  { number: 29, name: "29. Al-Ankabut (The Spider)", ayahs: 69 },
  { number: 30, name: "30. Ar-Rum (The Romans)", ayahs: 60 },
  { number: 31, name: "31. Luqman (Luqman)", ayahs: 34 },
  { number: 32, name: "32. As-Sajdah (The Prostration)", ayahs: 30 },
  { number: 33, name: "33. Al-Ahzab (The Combined Forces)", ayahs: 73 },
  { number: 34, name: "34. Saba (Sheba)", ayahs: 54 },
  { number: 35, name: "35. Fatir (Originator)", ayahs: 45 },
  { number: 36, name: "36. Ya-Sin (Ya Sin)", ayahs: 83 },
  { number: 37, name: "37. As-Saffat (Those Who Set The Ranks)", ayahs: 182 },
  { number: 38, name: "38. Sad (The Letter Sad)", ayahs: 88 },
  { number: 39, name: "39. Az-Zumar (The Troops)", ayahs: 75 },
  { number: 40, name: "40. Ghafir (The Forgiver)", ayahs: 85 },
  { number: 41, name: "41. Fussilat (Explained In Detail)", ayahs: 54 },
  { number: 42, name: "42. Ash-Shura (The Consultation)", ayahs: 53 },
  { number: 43, name: "43. Az-Zukhruf (The Gold Adornments)", ayahs: 89 },
  { number: 44, name: "44. Ad-Dukhan (The Smoke)", ayahs: 59 },
  { number: 45, name: "45. Al-Jathiyah (The Kneeling)", ayahs: 37 },
  { number: 46, name: "46. Al-Ahqaf (The Wind-Curved Sandhills)", ayahs: 35 },
  { number: 47, name: "47. Muhammad (Muhammad)", ayahs: 38 },
  { number: 48, name: "48. Al-Fath (The Victory)", ayahs: 29 },
  { number: 49, name: "49. Al-Hujurat (The Rooms)", ayahs: 18 },
  { number: 50, name: "50. Qaf (The Letter Qaf)", ayahs: 45 },
  { number: 51, name: "51. Adh-Dhariyat (The Winnowing Winds)", ayahs: 60 },
  { number: 52, name: "52. At-Tur (The Mount)", ayahs: 49 },
  { number: 53, name: "53. An-Najm (The Star)", ayahs: 62 },
  { number: 54, name: "54. Al-Qamar (The Moon)", ayahs: 55 },
  { number: 55, name: "55. Ar-Rahman (The Beneficent)", ayahs: 78 },
  { number: 56, name: "56. Al-Waqi'ah (The Inevitable)", ayahs: 96 },
  { number: 57, name: "57. Al-Hadid (The Iron)", ayahs: 29 },
  { number: 58, name: "58. Al-Mujadilah (The Pleading Woman)", ayahs: 22 },
  { number: 59, name: "59. Al-Hashr (The Exile)", ayahs: 24 },
  { number: 60, name: "60. Al-Mumtahanah (The Examined One)", ayahs: 13 },
  { number: 61, name: "61. As-Saff (The Ranks)", ayahs: 14 },
  { number: 62, name: "62. Al-Jumu'ah (Friday)", ayahs: 11 },
  { number: 63, name: "63. Al-Munafiqun (The Hypocrites)", ayahs: 11 },
  { number: 64, name: "64. At-Taghabun (The Mutual Disillusion)", ayahs: 18 },
  { number: 65, name: "65. At-Talaq (Divorce)", ayahs: 12 },
  { number: 66, name: "66. At-Tahrim (The Prohibition)", ayahs: 12 },
  { number: 67, name: "67. Al-Mulk (The Sovereignty)", ayahs: 30 },
  { number: 68, name: "68. Al-Qalam (The Pen)", ayahs: 52 },
  { number: 69, name: "69. Al-Haqqah (The Reality)", ayahs: 52 },
  { number: 70, name: "70. Al-Ma'arij (The Ascending Stairways)", ayahs: 44 },
  { number: 71, name: "71. Nuh (Noah)", ayahs: 28 },
  { number: 72, name: "72. Al-Jinn (The Jinn)", ayahs: 28 },
  { number: 73, name: "73. Al-Muzzammil (The Enshrouded One)", ayahs: 20 },
  { number: 74, name: "74. Al-Muddaththir (The Cloaked One)", ayahs: 56 },
  { number: 75, name: "75. Al-Qiyamah (The Resurrection)", ayahs: 40 },
  { number: 76, name: "76. Al-Insan (Man)", ayahs: 31 },
  { number: 77, name: "77. Al-Mursalat (The Emissaries)", ayahs: 50 },
  { number: 78, name: "78. An-Naba (The Tidings)", ayahs: 40 },
  { number: 79, name: "79. An-Nazi'at (Those Who Drag Forth)", ayahs: 46 },
  { number: 80, name: "80. Abasa (He Frowned)", ayahs: 42 },
  { number: 81, name: "81. At-Takwir (The Overthrowing)", ayahs: 29 },
  { number: 82, name: "82. Al-Infitar (The Cleaving)", ayahs: 19 },
  { number: 83, name: "83. Al-Mutaffifin (The Defrauders)", ayahs: 36 },
  { number: 84, name: "84. Al-Inshiqaq (The Sundering)", ayahs: 25 },
  { number: 85, name: "85. Al-Buruj (The Mansions of the Stars)", ayahs: 22 },
  { number: 86, name: "86. At-Tariq (The Nightcomer)", ayahs: 17 },
  { number: 87, name: "87. Al-A'la (The Most High)", ayahs: 19 },
  { number: 88, name: "88. Al-Ghashiyah (The Overwhelming)", ayahs: 26 },
  { number: 89, name: "89. Al-Fajr (The Dawn)", ayahs: 30 },
  { number: 90, name: "90. Al-Balad (The City)", ayahs: 20 },
  { number: 91, name: "91. Ash-Shams (The Sun)", ayahs: 15 },
  { number: 92, name: "92. Al-Layl (The Night)", ayahs: 21 },
  { number: 93, name: "93. Ad-Duha (The Morning Hours)", ayahs: 11 },
  { number: 94, name: "94. Ash-Sharh (The Relief)", ayahs: 8 },
  { number: 95, name: "95. At-Tin (The Fig)", ayahs: 8 },
  { number: 96, name: "96. Al-Alaq (The Clot)", ayahs: 19 },
  { number: 97, name: "97. Al-Qadr (The Power)", ayahs: 5 },
  { number: 98, name: "98. Al-Bayyinah (The Clear Proof)", ayahs: 8 },
  { number: 99, name: "99. Az-Zalzalah (The Earthquake)", ayahs: 8 },
  { number: 100, name: "100. Al-Adiyat (The Coursers)", ayahs: 11 },
  { number: 101, name: "101. Al-Qari'ah (The Calamity)", ayahs: 11 },
  { number: 102, name: "102. At-Takathur (The Rivalry in World Increase)", ayahs: 8 },
  { number: 103, name: "103. Al-Asr (The Declining Day)", ayahs: 3 },
  { number: 104, name: "104. Al-Humazah (The Traducer)", ayahs: 9 },
  { number: 105, name: "105. Al-Fil (The Elephant)", ayahs: 5 },
  { number: 106, name: "106. Quraysh (Quraysh)", ayahs: 4 },
  { number: 107, name: "107. Al-Ma'un (The Small Kindnesses)", ayahs: 7 },
  { number: 108, name: "108. Al-Kawthar (The Abundance)", ayahs: 3 },
  { number: 109, name: "109. Al-Kafirun (The Disbelievers)", ayahs: 6 },
  { number: 110, name: "110. An-Nasr (The Divine Support)", ayahs: 3 },
  { number: 111, name: "111. Al-Masad (The Palm Fiber)", ayahs: 5 },
  { number: 112, name: "112. Al-Ikhlas (The Sincerity)", ayahs: 4 },
  { number: 113, name: "113. Al-Falaq (The Daybreak)", ayahs: 5 },
  { number: 114, name: "114. An-Nas (Mankind)", ayahs: 6 },
]

// Helper function to get the number of ayahs for a given surah
export function getAyahCount(surahName: string): number {
  const surah = surahData.find((s) => s.name === surahName)
  return surah ? surah.ayahs : 0
}

// Helper function to generate a title from surah and ayah range
export function generateAssignmentTitle(surahName: string, startAyah: number, endAyah: number): string {
  // Extract just the surah name without the number and parentheses
  const surahNameOnly = surahName.replace(/^\d+\.\s+/, "").split(" (")[0]

  if (startAyah === endAyah) {
    return `${surahNameOnly} - Ayah ${startAyah}`
  }
  return `${surahNameOnly} - Ayahs ${startAyah}-${endAyah}`
}
